/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 exel.gltf 
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh, Group } from "three";
interface ModelProps {
  [key: string]: any;
  rotationX?: any;
  rotationY?: any;
  scale?: any;
}

export default function Model({
  rotationX,
  rotationY,
  scale,
  ...props
}: ModelProps) {
  const { nodes, materials } = useGLTF("/exel.glb");
  const groupRef = useRef<Group>(null);

  useEffect(() => {
    const unsubscribeY = rotationY?.onChange((latest: number) => {
      if (groupRef.current) {
        groupRef.current.rotation.y = latest;
      }
    });

    return () => unsubscribeY?.();
  }, [rotationY]);

  useEffect(() => {
    const unsubscribeX = rotationX?.onChange((latest: number) => {
      if (groupRef.current) {
        groupRef.current.rotation.x = latest;
      }
    });

    return () => unsubscribeX?.();
  }, [rotationX]);

  useEffect(() => {
    const unsubscribeScale = scale?.onChange((latest: number) => {
      if (groupRef.current) {
        groupRef.current.scale.set(latest, latest, latest);
      }
    });

    return () => unsubscribeScale?.();
  }, [scale]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={(nodes.tripo_node_92dd469b as Mesh).geometry}
        material={materials.tripo_mat_92dd469b}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/exel.glb");
